export const GET_INITIAL_DATA_SUCCESS = 'GET_INITIAL_DATA_SUCCESS';

export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';

export const ADD_MOVIE_SUCCESS = 'ADD_MOVIE_SUCCESS';

export const EDIT_MOVIE_SUCCESS = 'EDIT_MOVIE_SUCCESS';

export const DELETE_MOVIE_SUCCESS = 'DELETE_MOVIE_SUCCESS';

export const FILTER_MOVIE_SUCCESS = 'FILTER_MOVIE_SUCCESS';

export const SORT_MOVIE_SUCCESS = 'SORT_MOVIE_SUCCESS';

export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const SHOW_MODAL = 'SHOW_MODAL';
export const HIDE_MODAL = 'HIDE_MODAL';